// <auto-generated>
//   DMNware AppGen — do not hand-edit.
//   Source: FlappyBird.layout.cs
//   Manual edits are overwritten on regeneration.
//   To eject: delete the .layout.cs file.
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;
using TMPro;

public partial class FlappyBird
{
    [SerializeField] private UnityEngine.UI.Image bg;
    [SerializeField] private UnityEngine.UI.Image ground;
    [SerializeField] private UnityEngine.UI.Image pipeTop1;
    [SerializeField] private UnityEngine.UI.Image pipeBot1;
    [SerializeField] private UnityEngine.UI.Image pipeTop2;
    [SerializeField] private UnityEngine.UI.Image pipeBot2;
    [SerializeField] private UnityEngine.UI.Image pipeTop3;
    [SerializeField] private UnityEngine.UI.Image pipeBot3;
    [SerializeField] private UnityEngine.UI.Image bird;
    [SerializeField] private TMPro.TMP_Text title;
    [SerializeField] private TMPro.TMP_Text hint;
    [SerializeField] private TMPro.TMP_Text score;
    [SerializeField] private TMPro.TMP_Text gameOver;
    [SerializeField] private TMPro.TMP_Text bestText;
    [SerializeField] private UnityEngine.UI.Button flap;
    [SerializeField] private UnityEngine.UI.Button restart;
}
