// <auto-generated>
//   DMNware AppGen — do not hand-edit.
//   Source: Minesweeper.layout.cs
//   Manual edits are overwritten on regeneration.
//   To eject: delete the .layout.cs file.
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;
using TMPro;

public partial class Minesweeper
{
    [SerializeField] private UnityEngine.UI.Image bg;
    [SerializeField] private TMPro.TMP_Text minesText;
    [SerializeField] private TMPro.TMP_Text timerText;
    [SerializeField] private TMPro.TMP_Text statusText;
    [SerializeField] private UnityEngine.UI.Toggle flagToggle;
    [SerializeField] private UnityEngine.UI.Button newGame;
    [SerializeField] private UnityEngine.UI.Button cell00;
    [SerializeField] private UnityEngine.UI.Button cell01;
    [SerializeField] private UnityEngine.UI.Button cell02;
    [SerializeField] private UnityEngine.UI.Button cell03;
    [SerializeField] private UnityEngine.UI.Button cell04;
    [SerializeField] private UnityEngine.UI.Button cell05;
    [SerializeField] private UnityEngine.UI.Button cell06;
    [SerializeField] private UnityEngine.UI.Button cell07;
    [SerializeField] private UnityEngine.UI.Button cell10;
    [SerializeField] private UnityEngine.UI.Button cell11;
    [SerializeField] private UnityEngine.UI.Button cell12;
    [SerializeField] private UnityEngine.UI.Button cell13;
    [SerializeField] private UnityEngine.UI.Button cell14;
    [SerializeField] private UnityEngine.UI.Button cell15;
    [SerializeField] private UnityEngine.UI.Button cell16;
    [SerializeField] private UnityEngine.UI.Button cell17;
    [SerializeField] private UnityEngine.UI.Button cell20;
    [SerializeField] private UnityEngine.UI.Button cell21;
    [SerializeField] private UnityEngine.UI.Button cell22;
    [SerializeField] private UnityEngine.UI.Button cell23;
    [SerializeField] private UnityEngine.UI.Button cell24;
    [SerializeField] private UnityEngine.UI.Button cell25;
    [SerializeField] private UnityEngine.UI.Button cell26;
    [SerializeField] private UnityEngine.UI.Button cell27;
    [SerializeField] private UnityEngine.UI.Button cell30;
    [SerializeField] private UnityEngine.UI.Button cell31;
    [SerializeField] private UnityEngine.UI.Button cell32;
    [SerializeField] private UnityEngine.UI.Button cell33;
    [SerializeField] private UnityEngine.UI.Button cell34;
    [SerializeField] private UnityEngine.UI.Button cell35;
    [SerializeField] private UnityEngine.UI.Button cell36;
    [SerializeField] private UnityEngine.UI.Button cell37;
    [SerializeField] private UnityEngine.UI.Button cell40;
    [SerializeField] private UnityEngine.UI.Button cell41;
    [SerializeField] private UnityEngine.UI.Button cell42;
    [SerializeField] private UnityEngine.UI.Button cell43;
    [SerializeField] private UnityEngine.UI.Button cell44;
    [SerializeField] private UnityEngine.UI.Button cell45;
    [SerializeField] private UnityEngine.UI.Button cell46;
    [SerializeField] private UnityEngine.UI.Button cell47;
    [SerializeField] private UnityEngine.UI.Button cell50;
    [SerializeField] private UnityEngine.UI.Button cell51;
    [SerializeField] private UnityEngine.UI.Button cell52;
    [SerializeField] private UnityEngine.UI.Button cell53;
    [SerializeField] private UnityEngine.UI.Button cell54;
    [SerializeField] private UnityEngine.UI.Button cell55;
    [SerializeField] private UnityEngine.UI.Button cell56;
    [SerializeField] private UnityEngine.UI.Button cell57;
    [SerializeField] private UnityEngine.UI.Button cell60;
    [SerializeField] private UnityEngine.UI.Button cell61;
    [SerializeField] private UnityEngine.UI.Button cell62;
    [SerializeField] private UnityEngine.UI.Button cell63;
    [SerializeField] private UnityEngine.UI.Button cell64;
    [SerializeField] private UnityEngine.UI.Button cell65;
    [SerializeField] private UnityEngine.UI.Button cell66;
    [SerializeField] private UnityEngine.UI.Button cell67;
    [SerializeField] private UnityEngine.UI.Button cell70;
    [SerializeField] private UnityEngine.UI.Button cell71;
    [SerializeField] private UnityEngine.UI.Button cell72;
    [SerializeField] private UnityEngine.UI.Button cell73;
    [SerializeField] private UnityEngine.UI.Button cell74;
    [SerializeField] private UnityEngine.UI.Button cell75;
    [SerializeField] private UnityEngine.UI.Button cell76;
    [SerializeField] private UnityEngine.UI.Button cell77;
}
