// <auto-generated>
//   DMNware AppGen — do not hand-edit.
//   Source: Calculator.layout.cs
//   Manual edits are overwritten on regeneration.
//   To eject: delete the .layout.cs file.
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;
using TMPro;

public partial class Calculator
{
    [SerializeField] private TMPro.TMP_Text display;
    [SerializeField] private UnityEngine.UI.Button d7;
    [SerializeField] private UnityEngine.UI.Button d8;
    [SerializeField] private UnityEngine.UI.Button d9;
    [SerializeField] private UnityEngine.UI.Button div;
    [SerializeField] private UnityEngine.UI.Button d4;
    [SerializeField] private UnityEngine.UI.Button d5;
    [SerializeField] private UnityEngine.UI.Button d6;
    [SerializeField] private UnityEngine.UI.Button mul;
    [SerializeField] private UnityEngine.UI.Button d1;
    [SerializeField] private UnityEngine.UI.Button d2;
    [SerializeField] private UnityEngine.UI.Button d3;
    [SerializeField] private UnityEngine.UI.Button sub;
    [SerializeField] private UnityEngine.UI.Button clear;
    [SerializeField] private UnityEngine.UI.Button d0;
    [SerializeField] private UnityEngine.UI.Button dot;
    [SerializeField] private UnityEngine.UI.Button add;
    [SerializeField] private UnityEngine.UI.Button eq;
}
