// <auto-generated>
//   DMNware AppGen — do not hand-edit.
//   Source: Counter.layout.cs
//   Manual edits are overwritten on regeneration.
//   To eject: delete the .layout.cs file.
// </auto-generated>

using UnityEngine;
using UnityEngine.UI;
using TMPro;

public partial class Counter
{
    [SerializeField] private TMPro.TMP_Text count;
    [SerializeField] private UnityEngine.UI.Slider step;
    [SerializeField] private UnityEngine.UI.Toggle autoFive;
    [SerializeField] private UnityEngine.UI.Button dec;
    [SerializeField] private UnityEngine.UI.Button inc;
    [SerializeField] private UnityEngine.UI.Button reset;
}
