using System.Collections.Generic;
using System.IO;
using System.Text;

namespace DMNware.AppGen.Editor
{
    /// Emits MyApp.gen.cs — a partial-class file with [SerializeField] fields for every
    /// node in the layout that has an id.
    public static class PartialWriter
    {
        public struct FieldDecl
        {
            public string TypeName;     // e.g. "UnityEngine.UI.Button", "TMPro.TMP_Text"
            public string FieldName;    // node id
        }

        /// Returns the content of the .gen.cs file. Caller compares against existing on-disk
        /// content to decide whether a write is needed.
        public static string Render(string className, string layoutFileName, List<FieldDecl> fields)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   DMNware AppGen — do not hand-edit.");
            sb.AppendLine($"//   Source: {layoutFileName}");
            sb.AppendLine("//   Manual edits are overwritten on regeneration.");
            sb.AppendLine("//   To eject: delete the .layout.cs file.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine("using TMPro;");
            sb.AppendLine();
            sb.AppendLine($"public partial class {className}");
            sb.AppendLine("{");
            foreach (var f in fields)
            {
                sb.AppendLine($"    [SerializeField] private {f.TypeName} {f.FieldName};");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// Writes content if different from disk. Returns true if a write happened.
        public static bool WriteIfChanged(string path, string content)
        {
            if (File.Exists(path))
            {
                var existing = File.ReadAllText(path);
                if (existing == content) return false;
            }
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, content);
            return true;
        }
    }
}
